export { default as DivMonth } from "./DivMonth";
export { default as DivYear } from "./DivYear";
export { default as DivMonthDeth } from "./DivMonthDeth";
export { default as TableRegists } from "./TableRegists";
export { default as Modal } from "./Modal";
export { default as SectionWhite} from "./SectionWhite";
export { default as TopBar } from "./TopBar";
export { default as Buttons} from "./Buttons";
export { default as DivCards } from "./DivCards";
export { default as Card } from "./Card";
export { default as DivGeneric } from "./DivGeneric";
export { default as Form } from "./Form";
export { default as Inputs } from "./Inputs";
export { default as Selects} from "./Selects";
export { default as FormAddRegister} from "./FormAddRegister";
export { default as CardDash } from "./CardDash";
export { default as ConteinnerDay } from "./ConteinnerDay";
export { default as DivItem } from "./DivItem";
export { default as CicloButtons } from "./CicloButtons";
export { default as LabelSituation} from "./LabelSituation";
export { default as SpanValue} from "./SpanValue";
export { default as FormAlterItem } from "./FormAlterItem";
export { default as CardDashYear} from "./CardDashYear";
export { default as DivDashYear} from "./DivDashYear";
export { default as TableYear} from "./TableYear";