export { default as DivMonth } from "./DivMonth";
export { default as DivYear } from "./DivYear";
export { default as DivMonthDeth } from "./DivMonthDeth";
export { default as TableRegists } from "./TableRegists";
export { default as Modal } from "./Modal";
export { default as SectionWhite} from "./SectionWhite";
export { default as TopBar } from "./TopBar";
export { default as Buttons} from "./Buttons";
export { default as DivCards } from "./DivCards";
export { default as Card } from "./Card";
export { default as DivGeneric } from "./DivGeneric";